name: "New Version"

on:
  push:
    branches:
      - main

# Automatically create a new version and update Changelog.md by closing a pull request to main
jobs:
  release:
    name: "Release - GitHub"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: show Version
        run: echo ${{ steps.package-version.outputs.current-version}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
          prerelease: false
