name: "New Version"

on:
  push:
    branches:
      - main

# Automatically create a new version and update Changelog.md by closing a pull request to main
jobs:
  prepare-release:
    name: "Prepare Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Update Version
        run: npm run update-version
  release:
    name: "Release - GitHub"
    runs-on: "ubuntu-latest"
    needs: prepare-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: show Version
        run: echo ${{ steps.package-version.outputs.current-version}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
          prerelease: false
