name: "Release"

on:
  push:
    tags:
      - "v*"

# Automatically create a new version and update Changelog.md by closing a pull request to main
jobs:
  release:
    name: "Release - GitHub"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
